/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskFormRouteImport } from './routes/TaskForm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskItemIdRouteImport } from './routes/TaskItem/$id'
import { Route as TaskItemTaskItemEditIdRouteImport } from './routes/TaskItem/TaskItemEdit/$id'

const TaskFormRoute = TaskFormRouteImport.update({
  id: '/TaskForm',
  path: '/TaskForm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskItemIdRoute = TaskItemIdRouteImport.update({
  id: '/TaskItem/$id',
  path: '/TaskItem/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskItemTaskItemEditIdRoute = TaskItemTaskItemEditIdRouteImport.update({
  id: '/TaskItem/TaskItemEdit/$id',
  path: '/TaskItem/TaskItemEdit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/TaskForm': typeof TaskFormRoute
  '/TaskItem/$id': typeof TaskItemIdRoute
  '/TaskItem/TaskItemEdit/$id': typeof TaskItemTaskItemEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/TaskForm': typeof TaskFormRoute
  '/TaskItem/$id': typeof TaskItemIdRoute
  '/TaskItem/TaskItemEdit/$id': typeof TaskItemTaskItemEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/TaskForm': typeof TaskFormRoute
  '/TaskItem/$id': typeof TaskItemIdRoute
  '/TaskItem/TaskItemEdit/$id': typeof TaskItemTaskItemEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/TaskForm' | '/TaskItem/$id' | '/TaskItem/TaskItemEdit/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/TaskForm' | '/TaskItem/$id' | '/TaskItem/TaskItemEdit/$id'
  id:
    | '__root__'
    | '/'
    | '/TaskForm'
    | '/TaskItem/$id'
    | '/TaskItem/TaskItemEdit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskFormRoute: typeof TaskFormRoute
  TaskItemIdRoute: typeof TaskItemIdRoute
  TaskItemTaskItemEditIdRoute: typeof TaskItemTaskItemEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/TaskForm': {
      id: '/TaskForm'
      path: '/TaskForm'
      fullPath: '/TaskForm'
      preLoaderRoute: typeof TaskFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TaskItem/$id': {
      id: '/TaskItem/$id'
      path: '/TaskItem/$id'
      fullPath: '/TaskItem/$id'
      preLoaderRoute: typeof TaskItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TaskItem/TaskItemEdit/$id': {
      id: '/TaskItem/TaskItemEdit/$id'
      path: '/TaskItem/TaskItemEdit/$id'
      fullPath: '/TaskItem/TaskItemEdit/$id'
      preLoaderRoute: typeof TaskItemTaskItemEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskFormRoute: TaskFormRoute,
  TaskItemIdRoute: TaskItemIdRoute,
  TaskItemTaskItemEditIdRoute: TaskItemTaskItemEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
